// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AuctionApp.Models;

[Table("__EFMigrationsLock")]
public partial class __EFMigrationsLock
{
    [Key]
    public int Id { get; set; }

    [Required]
    public string Timestamp { get; set; }
}