// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace AuctionApp.Models;

public partial class AuctionAppDataauctiondbContext : DbContext
{
    public AuctionAppDataauctiondbContext()
    {
    }

    public AuctionAppDataauctiondbContext(DbContextOptions<AuctionAppDataauctiondbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Bid> Bids { get; set; }

    public virtual DbSet<IdentityUser> IdentityUsers { get; set; }

    public virtual DbSet<Listing> Listings { get; set; }

    public virtual DbSet<__EFMigrationsLock> __EFMigrationsLocks { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlite("Data Source=C:\\Users\\brett\\Desktop\\Code-You-Auction-App-Final-Project\\AuctionApp\\AuctionApp\\Data\\auction.db");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<__EFMigrationsLock>(entity =>
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}