// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace AuctionApp.Models;

[Index("IdentityUserId", Name = "IX_Bids_IdentityUserId")]
[Index("ListingId", Name = "IX_Bids_ListingId")]
public partial class Bid
{
    [Key]
    public int BidId { get; set; }

    [Column(TypeName = "money")]
    public decimal StartingBid { get; set; }

    [Required]
    public string IdentityUserId { get; set; }

    public int ListingId { get; set; }

    [ForeignKey("IdentityUserId")]
    [InverseProperty("Bids")]
    public virtual IdentityUser IdentityUser { get; set; }

    [ForeignKey("ListingId")]
    [InverseProperty("Bids")]
    public virtual Listing Listing { get; set; }
}